DROP SEQUENCE MEMBERSEQ;
DROP TABLE TB_MEMBER;

CREATE SEQUENCE MEMBERSEQ;

CREATE TABLE TB_MEMBER(
	M_NO NUMBER PRIMARY KEY,
	M_NAME VARCHAR2(100) NOT NULL,
	M_AGE NUMBER NOT NULL,
	M_GENDER VARCHAR2(2) CHECK(M_GENDER IN('M','F')) NOT NULL,
	M_LOCATION VARCHAR2(100),
	M_JOB VARCHAR2(20),
	M_TEL VARCHAR2(20),
	M_EMAIL VARCHAR2(20)
);

INSERT INTO TB_MEMBER VALUES (MEMBERSEQ.NEXTVAL, '강여림', 29, 'F', '경기도 광주', '학생', '010-5772-9708','YR@.NAVER.COM');

SELECT M_NO, M_NAME, M_AGE, M_GENDER, M_LOCATION, M_JOB, M_TEL, M_EMAIL FROM TB_MEMBER;
