DROP SEQUENCE MDBOARDSEQ;
DROP TABLE MDBOARD;

CREATE SEQUENCE MDBOARDSEQ;

CREATE TABLE MDBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MDBOARD VALUES (MDBOARDSEQ.NEXTVAL, '관리자', 'TEST 글 입니다.','TEST1234',SYSDATE);

INSERT INTO MDBOARD VALUES (MDBOARDSEQ.NEXTVAL, '둥이','언니 진짜','나 댕댕열차 타고 싶어 돈줘',SYSDATE);

SELECT * FROM MDBOARD ORDER BY SEQ DESC;


