DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL, '이제훈', '제목1', '내용1', SYSDATE);
INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL, '서강준', '제목2', '내용2', SYSDATE);
INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL, '지창욱', '제목3', '내용3', SYSDATE);
INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL, '조인성', '제목4', '내용4', SYSDATE);
INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL, '여진구', '제목5', '내용5', SYSDATE);


SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
FROM MYBOARD
ORDER BY MYNO DESC;