DROP SEQUENCE MVCBOARDSEQ
DROP TABLE MVCBOARD

CREATE SEQUENCE MVCBOARDSEQ;
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES(MVCBOARDSEQ.NEXTVAL, '관리자','TEST글 입니다','TEST1234',SYSDATE);
INSERT INTO MVCBOARD VALUES(MVCBOARDSEQ.NEXTVAL, '강여림','배고파','칼국수 먹고싶다',SYSDATE);

SELECT * FROM MVCBOARD ORDER BY SEQ DESC;

